repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        files: "^bindings/node/.+"
        exclude: "^clients/js/src/generated/.+"
        additional_dependencies:
          - prettier@2.8.7