name: Build MacOS Binaries

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        type: string

jobs:
  macOS-latest-cmake-arm64:
    runs-on: macos-14
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Dependencies
        id: depends
        continue-on-error: true
        run: |
          brew update

      - name: Build and Test
        id: cmake_build
        run: |
          export CMAKE_FLAGS="-DGGML_METAL_EMBED_LIBRARY=ON"
          export CMAKE_BUILD_FLAGS="-j $(sysctl -n hw.logicalcpu)"
          sysctl -a
          make lib-test


      - name: Pack artifacts
        id: pack_artifacts
        run: |
          cp LICENSE ./build/bin/
          zip -r llama-embedder-${{ inputs.tag }}-macos-arm64.zip ./build/libllama-embedder.*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: llama-embedder-${{ inputs.tag }}-macos-arm64.zip
          name: llama-embedder-macos-arm64.zip

  macOS-latest-cmake-x64:
    runs-on: macos-12

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Dependencies
        id: depends
        continue-on-error: true
        run: |
          brew update

      - name: Build
        id: cmake_build
        run: |
          export CMAKE_FLAGS="-DGGML_METAL_EMBED_LIBRARY=ON"
          export CMAKE_BUILD_FLAGS="-j $(sysctl -n hw.logicalcpu)"
          sysctl -a
          # Metal is disabled due to intermittent failures with Github runners not having a GPU:
          # https://github.com/ggerganov/llama.cpp/actions/runs/8635935781/job/23674807267#step:5:2313
          make lib-test

      - name: Pack artifacts
        id: pack_artifacts
        run: |
          cp LICENSE ./build/bin/
          zip -r llama-embedder-${{ inputs.tag }}-macos-x64.zip ./build/llama-embedder.*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: llama-embedder-${{ inputs.tag  }}-macos-x64.zip
          name: llama-embedder-bin-macos-x64.zip

          