name: Build MacOS Binaries

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        type: string

jobs:
  macOS-latest-cmake-arm64:
    runs-on: macos-14
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Dependencies
        id: depends
        continue-on-error: true
        run: |
          brew update

      - name: Build and Test
        id: cmake_build
        run: |
          export CMAKE_FLAGS="-DGGML_METAL_EMBED_LIBRARY=ON -DLLAMA_METAL=ON"
          export CMAKE_BUILD_FLAGS="-j $(sysctl -n hw.logicalcpu)"
          sysctl -a
          make lib-static-test


      - name: Pack artifacts
        id: pack_artifacts
        run: |
          mkdir artifact-pack
          cp -r ./build/static/*.a ./artifact-pack
          cp ./LICENSE.md ./artifact-pack
          cp ./vendor/llama.cpp/LICENSE ./artifact-pack/LICENSE-llamacpp
          tar -czf llama-embedder-static-macos-arm64-${{ inputs.tag }}.tar.gz -C ./artifact-pack .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: llama-embedder-static-macos-arm64-${{ inputs.tag }}.tar.gz
          name: llama-embedder-static-macos-arm64

  macOS-latest-cmake-x64:
    runs-on: macos-12

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Dependencies
        id: depends
        continue-on-error: true
        run: |
          brew update

      - name: Build
        id: cmake_build
        run: |
          export CMAKE_FLAGS="-DGGML_METAL_EMBED_LIBRARY=ON -DLLAMA_METAL=ON"
          export CMAKE_BUILD_FLAGS="-j $(sysctl -n hw.logicalcpu)"
          sysctl -a
          make lib-static-test

      - name: Pack artifacts
        id: pack_artifacts
        run: |
          mkdir artifact-pack
          cp -r ./build/static/*.a ./artifact-pack
          cp ./LICENSE.md ./artifact-pack
          cp ./vendor/llama.cpp/LICENSE ./artifact-pack/LICENSE-llamacpp
          tar -czf llama-embedder-static-macos-arm64-${{ inputs.tag }}.tar.gz -C ./artifact-pack .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: llama-embedder-static-macos-x64-${{ inputs.tag }}.tar.gz
          name: llama-embedder-static-macos-x64

          